server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/registration
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: formmcit2023@gmail.com
    password: myownpassword
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true